apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-jenkins-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-jenkins-docker
  template:
    metadata:
      labels:
        app: react-jenkins-docker
    spec:
      containers:
      - name: react-jenkins-docker
        image: ${ImageRegistry}:${BUILD_NUMBER}
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: react-jenkins-docker-service
spec:
  type: NodePort
  selector:
    app: react-jenkins-docker
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30080
